name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.7.2'
        modules: qtnetworkauth qt5compat

    - name: Install system deps
      run: sudo apt-get update && sudo apt-get install -y libquazip1-qt6-dev libgl1-mesa-dev

    - name: Configure project
      run: cmake -S Google-Drive-Client -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build project
      run: cmake --build build
